# Generated by Django 6.0.6 on 2026-06-09 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, unique=True
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                ("receiver_name", models.CharField(max_length=255)),
                (
                    "receiver_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("destination", models.TextField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estimated_delivery", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrackingHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("DELAYED", "Delayed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="core.cargo",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
